config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	devise_scope :user do
		root to: 'devise/sessions#new'
		get 'login', to: 'devise/sessions#new'
		delete 'logout', to: 'devise/sessions#destroy'
	end

	resources :portals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :rememberable
  devise :database_authenticatable, :registerable, :recoverable, :validatable
  
  validate :validate_password
  

  enum role: [:admin, :user]


  def set_role(role)
  	update(role: role)
  end

  def validate_password
  	reg = /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}\z/
  	unless reg.match(password)
  		errors.add(:password, "Password contains minimum eight characters, at least one uppercase letter, one lowercase letter and one number")
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :check_user_role
	before_action :authenticate_user!
	
	def after_sign_in_path_for(resources)
		portals_path
	end

	def after_sign_out_path_for(resources)
		new_user_session_path
	end
	
	def check_user_role
		if current_user
		  	unless current_user.admin?
				flash[:alert] = "You dont have permission to access this tab. Please contact Administrator."
				sign_out(current_user)
				redirect_to new_user_session_path
		  	end
		end
	end
end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
	
	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/layouts/_flash_messages.html.erb
<%= content_tag 'p', (flash[:notice] || flash[:success]).html_safe, class: 'alert alert-success alert-dismissible' if flash[:notice] || flash[:success] %>
<%= content_tag 'p', (flash[:error] || flash[:alert]).html_safe, class: 'alert alert-danger alert-dismissible' if flash[:error] || flash[:alert] %>
<% flash.clear if(request.path.split("/").last != "thank-you") %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
  	<div class="container-fluid">
		<div class="navbar-header">
	  		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
	  		</button>
	  		<%= link_to portals_path, class: 'navbar-brand' do %>
				Medidata User Portal
	  		<% end %>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
	  		<ul class="nav navbar-nav">
				
	  		</ul>
	  		<ul class="nav navbar-nav navbar-right">
	  			<% if user_signed_in? %>
					<li>
						<%= link_to logout_path, method: :delete do %>
		  					Sign Out
						<% end %>
					</li>
	  			<% end %>
	  		</ul>
		</div>
  	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"> 
    <meta name=viewport content="width=device-width, initial-scale=1">
    <title>iMedidata</title>
    <meta name="robots" content="noindex" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <% if user_signed_in? %>
        <%= render partial: "layouts/header" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/portals/index.html.erb
<div class="container">
	<h2>Users Data </h2>

	<div class="user_data">
		<table class="table table-bordered">
			<tr>
				<th scope="col">#</th>
				<th scope="col">Email</th>
				<th scope="col">Role</th>
			</tr>
			<% @users.each do |user| %>
				<tr>
					<td scope="row"><%= user.id %></td>
					<td scope="row"><%= user.email %></td>
					<td scope="row"><%= user.role %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Return to Medidata login", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "I forgot my username or password", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>